# Generated by Django 4.2.1 on 2023-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrsipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('fact_qliq_data1', models.IntegerField()),
                ('fact_qliq_data2', models.IntegerField()),
                ('fact_qoil_data1', models.IntegerField()),
                ('fact_qoil_data2', models.IntegerField()),
                ('forecast_qliq_data1', models.IntegerField()),
                ('forecast_qliq_data2', models.IntegerField()),
                ('forecast_qoil_data1', models.IntegerField()),
                ('forecast_qoil_data2', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('total_qliq', models.IntegerField(null=True)),
                ('total_qoil', models.IntegerField(null=True)),
            ],
        ),
    ]
